# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'COcalc_mainwindow.ui'
#
# Created: Tue Dec 06 16:28:32 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(799, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_CO = QtGui.QLabel(self.centralwidget)
        self.label_CO.setGeometry(QtCore.QRect(480, 430, 121, 20))
        self.label_CO.setObjectName(_fromUtf8("label_CO"))
        self.peakTime = QtGui.QPlainTextEdit(self.centralwidget)
        self.peakTime.setGeometry(QtCore.QRect(600, 460, 50, 24))
        self.peakTime.setMouseTracking(False)
        self.peakTime.setObjectName(_fromUtf8("peakTime"))
        self.label_tinterval = QtGui.QLabel(self.centralwidget)
        self.label_tinterval.setGeometry(QtCore.QRect(180, 520, 91, 20))
        self.label_tinterval.setObjectName(_fromUtf8("label_tinterval"))
        self.label_baseline = QtGui.QLabel(self.centralwidget)
        self.label_baseline.setGeometry(QtCore.QRect(310, 520, 46, 20))
        self.label_baseline.setObjectName(_fromUtf8("label_baseline"))
        self.label_sterror = QtGui.QLabel(self.centralwidget)
        self.label_sterror.setGeometry(QtCore.QRect(660, 430, 51, 20))
        self.label_sterror.setObjectName(_fromUtf8("label_sterror"))
        self.label_HUConversion = QtGui.QLabel(self.centralwidget)
        self.label_HUConversion.setGeometry(QtCore.QRect(180, 560, 141, 16))
        self.label_HUConversion.setObjectName(_fromUtf8("label_HUConversion"))
        self.label_bloodHU = QtGui.QLabel(self.centralwidget)
        self.label_bloodHU.setGeometry(QtCore.QRect(30, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_bloodHU.setFont(font)
        self.label_bloodHU.setObjectName(_fromUtf8("label_bloodHU"))
        self.plotwidget = MatplotlibWidget(self.centralwidget)
        self.plotwidget.setGeometry(QtCore.QRect(170, 40, 601, 381))
        self.plotwidget.setObjectName(_fromUtf8("plotwidget"))
        self.CurveFitResults = QtGui.QGroupBox(self.centralwidget)
        self.CurveFitResults.setGeometry(QtCore.QRect(180, 420, 271, 80))
        self.CurveFitResults.setObjectName(_fromUtf8("CurveFitResults"))
        self.label_rsquared = QtGui.QLabel(self.CurveFitResults)
        self.label_rsquared.setGeometry(QtCore.QRect(180, 20, 31, 16))
        self.label_rsquared.setObjectName(_fromUtf8("label_rsquared"))
        self.alpha = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.alpha.setGeometry(QtCore.QRect(20, 40, 40, 24))
        self.alpha.setMouseTracking(False)
        self.alpha.setObjectName(_fromUtf8("alpha"))
        self.rsquared = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.rsquared.setGeometry(QtCore.QRect(170, 40, 40, 24))
        self.rsquared.setMouseTracking(False)
        self.rsquared.setObjectName(_fromUtf8("rsquared"))
        self.beta = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.beta.setGeometry(QtCore.QRect(70, 40, 40, 24))
        self.beta.setMouseTracking(False)
        self.beta.setObjectName(_fromUtf8("beta"))
        self.AUC = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.AUC.setGeometry(QtCore.QRect(220, 40, 40, 24))
        self.AUC.setMouseTracking(False)
        self.AUC.setObjectName(_fromUtf8("AUC"))
        self.label_beta = QtGui.QLabel(self.CurveFitResults)
        self.label_beta.setGeometry(QtCore.QRect(80, 20, 31, 16))
        self.label_beta.setObjectName(_fromUtf8("label_beta"))
        self.label_alpha = QtGui.QLabel(self.CurveFitResults)
        self.label_alpha.setGeometry(QtCore.QRect(30, 20, 31, 16))
        self.label_alpha.setObjectName(_fromUtf8("label_alpha"))
        self.label_toffset = QtGui.QLabel(self.CurveFitResults)
        self.label_toffset.setGeometry(QtCore.QRect(130, 20, 31, 16))
        self.label_toffset.setObjectName(_fromUtf8("label_toffset"))
        self.t0 = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.t0.setGeometry(QtCore.QRect(120, 40, 40, 24))
        self.t0.setMouseTracking(False)
        self.t0.setObjectName(_fromUtf8("t0"))
        self.label_AUC = QtGui.QLabel(self.CurveFitResults)
        self.label_AUC.setGeometry(QtCore.QRect(230, 20, 31, 16))
        self.label_AUC.setObjectName(_fromUtf8("label_AUC"))
        self.MTT = QtGui.QPlainTextEdit(self.centralwidget)
        self.MTT.setGeometry(QtCore.QRect(600, 490, 50, 24))
        self.MTT.setMouseTracking(False)
        self.MTT.setObjectName(_fromUtf8("MTT"))
        self.standardError = QtGui.QPlainTextEdit(self.centralwidget)
        self.standardError.setGeometry(QtCore.QRect(710, 430, 40, 24))
        self.standardError.setMouseTracking(False)
        self.standardError.setObjectName(_fromUtf8("standardError"))
        self.HUtoIodineConversion = QtGui.QPlainTextEdit(self.centralwidget)
        self.HUtoIodineConversion.setGeometry(QtCore.QRect(360, 560, 40, 24))
        self.HUtoIodineConversion.setMouseTracking(False)
        self.HUtoIodineConversion.setObjectName(_fromUtf8("HUtoIodineConversion"))
        self.baselineInput = QtGui.QPlainTextEdit(self.centralwidget)
        self.baselineInput.setGeometry(QtCore.QRect(360, 520, 40, 24))
        self.baselineInput.setMouseTracking(False)
        self.baselineInput.setObjectName(_fromUtf8("baselineInput"))
        self.HUvalues = QtGui.QTableWidget(self.centralwidget)
        self.HUvalues.setGeometry(QtCore.QRect(20, 40, 141, 571))
        self.HUvalues.setMouseTracking(True)
        self.HUvalues.setRowCount(20)
        self.HUvalues.setColumnCount(1)
        self.HUvalues.setObjectName(_fromUtf8("HUvalues"))
        self.HUvalues.horizontalHeader().setVisible(False)
        self.HUvalues.horizontalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setVisible(True)
        self.HUvalues.verticalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setSortIndicatorShown(False)
        self.label_peaktime = QtGui.QLabel(self.centralwidget)
        self.label_peaktime.setGeometry(QtCore.QRect(480, 460, 81, 16))
        self.label_peaktime.setObjectName(_fromUtf8("label_peaktime"))
        self.label_timedensitycurve = QtGui.QLabel(self.centralwidget)
        self.label_timedensitycurve.setGeometry(QtCore.QRect(350, 20, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timedensitycurve.setFont(font)
        self.label_timedensitycurve.setObjectName(_fromUtf8("label_timedensitycurve"))
        self.cardiacOutput = QtGui.QPlainTextEdit(self.centralwidget)
        self.cardiacOutput.setGeometry(QtCore.QRect(600, 430, 50, 24))
        self.cardiacOutput.setMouseTracking(False)
        self.cardiacOutput.setReadOnly(True)
        self.cardiacOutput.setObjectName(_fromUtf8("cardiacOutput"))
        self.label_MTT = QtGui.QLabel(self.centralwidget)
        self.label_MTT.setGeometry(QtCore.QRect(480, 490, 111, 16))
        self.label_MTT.setObjectName(_fromUtf8("label_MTT"))
        self.timeInterval = QtGui.QPlainTextEdit(self.centralwidget)
        self.timeInterval.setGeometry(QtCore.QRect(260, 520, 40, 24))
        self.timeInterval.setMouseTracking(False)
        self.timeInterval.setObjectName(_fromUtf8("timeInterval"))
        self.reset = QtGui.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(490, 600, 75, 23))
        self.reset.setObjectName(_fromUtf8("reset"))
        self.apply = QtGui.QPushButton(self.centralwidget)
        self.apply.setGeometry(QtCore.QRect(620, 600, 75, 23))
        self.apply.setObjectName(_fromUtf8("apply"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_CO.setText(_translate("MainWindow", "Cardiac Output (L/min)", None))
        self.label_tinterval.setText(_translate("MainWindow", "Time Interval (s)", None))
        self.label_baseline.setText(_translate("MainWindow", "Baseline", None))
        self.label_sterror.setText(_translate("MainWindow", "st. error", None))
        self.label_HUConversion.setText(_translate("MainWindow", "HU/Iodine (HU/(mg/mL)) ", None))
        self.label_bloodHU.setText(_translate("MainWindow", "Blood Hounsfield Units", None))
        self.CurveFitResults.setTitle(_translate("MainWindow", "Curve Fit Results", None))
        self.label_rsquared.setText(_translate("MainWindow", "R^2", None))
        self.label_beta.setText(_translate("MainWindow", "beta", None))
        self.label_alpha.setText(_translate("MainWindow", "alpha", None))
        self.label_toffset.setText(_translate("MainWindow", "t0 (s)", None))
        self.label_AUC.setText(_translate("MainWindow", "AUC", None))
        self.label_peaktime.setText(_translate("MainWindow", "Time to Peak (s)", None))
        self.label_timedensitycurve.setText(_translate("MainWindow", "Time Density Curve", None))
        self.label_MTT.setText(_translate("MainWindow", "Mean Transit Time (s)", None))
        self.reset.setText(_translate("MainWindow", "Reset", None))
        self.apply.setText(_translate("MainWindow", "Apply", None))

from matplotlibwidget import MatplotlibWidget
