# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cocalc_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_CO = QtWidgets.QLabel(self.centralwidget)
        self.label_CO.setGeometry(QtCore.QRect(580, 420, 121, 20))
        self.label_CO.setObjectName("label_CO")
        self.peakTime = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.peakTime.setGeometry(QtCore.QRect(700, 450, 50, 24))
        self.peakTime.setMouseTracking(False)
        self.peakTime.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.peakTime.setObjectName("peakTime")
        self.label_tinterval = QtWidgets.QLabel(self.centralwidget)
        self.label_tinterval.setGeometry(QtCore.QRect(180, 520, 91, 20))
        self.label_tinterval.setObjectName("label_tinterval")
        self.label_baseline = QtWidgets.QLabel(self.centralwidget)
        self.label_baseline.setGeometry(QtCore.QRect(310, 520, 46, 20))
        self.label_baseline.setObjectName("label_baseline")
        self.label_sterror = QtWidgets.QLabel(self.centralwidget)
        self.label_sterror.setGeometry(QtCore.QRect(630, 510, 51, 20))
        self.label_sterror.setObjectName("label_sterror")
        self.label_HUConversion = QtWidgets.QLabel(self.centralwidget)
        self.label_HUConversion.setGeometry(QtCore.QRect(180, 560, 141, 16))
        self.label_HUConversion.setObjectName("label_HUConversion")
        self.label_bloodHU = QtWidgets.QLabel(self.centralwidget)
        self.label_bloodHU.setGeometry(QtCore.QRect(30, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_bloodHU.setFont(font)
        self.label_bloodHU.setObjectName("label_bloodHU")
        self.CurveFitResults = QtWidgets.QGroupBox(self.centralwidget)
        self.CurveFitResults.setGeometry(QtCore.QRect(160, 420, 391, 80))
        self.CurveFitResults.setObjectName("CurveFitResults")
        self.label_rsquared = QtWidgets.QLabel(self.CurveFitResults)
        self.label_rsquared.setGeometry(QtCore.QRect(180, 20, 31, 16))
        self.label_rsquared.setObjectName("label_rsquared")
        self.alpha = QtWidgets.QPlainTextEdit(self.CurveFitResults)
        self.alpha.setGeometry(QtCore.QRect(20, 40, 40, 24))
        self.alpha.setMouseTracking(False)
        self.alpha.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.alpha.setObjectName("alpha")
        self.rsquared = QtWidgets.QPlainTextEdit(self.CurveFitResults)
        self.rsquared.setGeometry(QtCore.QRect(170, 40, 51, 24))
        self.rsquared.setMouseTracking(False)
        self.rsquared.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.rsquared.setObjectName("rsquared")
        self.beta = QtWidgets.QPlainTextEdit(self.CurveFitResults)
        self.beta.setGeometry(QtCore.QRect(70, 40, 40, 24))
        self.beta.setMouseTracking(False)
        self.beta.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.beta.setObjectName("beta")
        self.AUC = QtWidgets.QPlainTextEdit(self.CurveFitResults)
        self.AUC.setGeometry(QtCore.QRect(240, 40, 141, 24))
        self.AUC.setMouseTracking(False)
        self.AUC.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.AUC.setObjectName("AUC")
        self.label_beta = QtWidgets.QLabel(self.CurveFitResults)
        self.label_beta.setGeometry(QtCore.QRect(80, 20, 31, 16))
        self.label_beta.setObjectName("label_beta")
        self.label_alpha = QtWidgets.QLabel(self.CurveFitResults)
        self.label_alpha.setGeometry(QtCore.QRect(30, 20, 31, 16))
        self.label_alpha.setObjectName("label_alpha")
        self.label_toffset = QtWidgets.QLabel(self.CurveFitResults)
        self.label_toffset.setGeometry(QtCore.QRect(130, 20, 31, 16))
        self.label_toffset.setObjectName("label_toffset")
        self.t0 = QtWidgets.QPlainTextEdit(self.CurveFitResults)
        self.t0.setGeometry(QtCore.QRect(120, 40, 40, 24))
        self.t0.setMouseTracking(False)
        self.t0.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.t0.setObjectName("t0")
        self.label_AUC = QtWidgets.QLabel(self.CurveFitResults)
        self.label_AUC.setGeometry(QtCore.QRect(230, 20, 31, 16))
        self.label_AUC.setObjectName("label_AUC")
        self.MTT = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.MTT.setGeometry(QtCore.QRect(700, 480, 50, 24))
        self.MTT.setMouseTracking(False)
        self.MTT.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.MTT.setObjectName("MTT")
        self.standardError = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.standardError.setGeometry(QtCore.QRect(699, 510, 51, 24))
        self.standardError.setMouseTracking(False)
        self.standardError.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.standardError.setObjectName("standardError")
        self.HUtoIodineConversion = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.HUtoIodineConversion.setGeometry(QtCore.QRect(360, 560, 40, 24))
        self.HUtoIodineConversion.setMouseTracking(False)
        self.HUtoIodineConversion.setObjectName("HUtoIodineConversion")
        self.baselineInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.baselineInput.setGeometry(QtCore.QRect(360, 520, 40, 24))
        self.baselineInput.setMouseTracking(False)
        self.baselineInput.setObjectName("baselineInput")
        self.HUvalues = QtWidgets.QTableWidget(self.centralwidget)
        self.HUvalues.setGeometry(QtCore.QRect(20, 40, 131, 611))
        self.HUvalues.setMouseTracking(True)
        self.HUvalues.setRowCount(20)
        self.HUvalues.setColumnCount(1)
        self.HUvalues.setObjectName("HUvalues")
        self.HUvalues.horizontalHeader().setVisible(False)
        self.HUvalues.horizontalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setVisible(True)
        self.HUvalues.verticalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setSortIndicatorShown(False)
        self.label_peaktime = QtWidgets.QLabel(self.centralwidget)
        self.label_peaktime.setGeometry(QtCore.QRect(580, 450, 81, 16))
        self.label_peaktime.setObjectName("label_peaktime")
        self.label_timedensitycurve = QtWidgets.QLabel(self.centralwidget)
        self.label_timedensitycurve.setGeometry(QtCore.QRect(380, 20, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timedensitycurve.setFont(font)
        self.label_timedensitycurve.setObjectName("label_timedensitycurve")
        self.cardiacOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cardiacOutput.setGeometry(QtCore.QRect(700, 420, 50, 24))
        self.cardiacOutput.setMouseTracking(False)
        self.cardiacOutput.setReadOnly(True)
        self.cardiacOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.cardiacOutput.setObjectName("cardiacOutput")
        self.label_MTT = QtWidgets.QLabel(self.centralwidget)
        self.label_MTT.setGeometry(QtCore.QRect(580, 480, 111, 16))
        self.label_MTT.setObjectName("label_MTT")
        self.timeInterval = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.timeInterval.setGeometry(QtCore.QRect(260, 520, 40, 24))
        self.timeInterval.setMouseTracking(False)
        self.timeInterval.setObjectName("timeInterval")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(580, 630, 75, 23))
        self.reset.setObjectName("reset")
        self.apply = QtWidgets.QPushButton(self.centralwidget)
        self.apply.setGeometry(QtCore.QRect(670, 630, 75, 23))
        self.apply.setObjectName("apply")
        self.GraphicsView = PlotWidget(self.centralwidget)
        self.GraphicsView.setGeometry(QtCore.QRect(180, 60, 571, 351))
        self.GraphicsView.setObjectName("GraphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CO Calculator"))
        self.label_CO.setText(_translate("MainWindow", "Cardiac Output (L/min)"))
        self.label_tinterval.setText(_translate("MainWindow", "Time Interval (s)"))
        self.label_baseline.setText(_translate("MainWindow", "Baseline"))
        self.label_sterror.setText(_translate("MainWindow", "st. error"))
        self.label_HUConversion.setText(_translate("MainWindow", "HU/Iodine (HU/(mg/mL)) "))
        self.label_bloodHU.setText(_translate("MainWindow", "Blood Hounsfield Units"))
        self.CurveFitResults.setTitle(_translate("MainWindow", "Curve Fit Results"))
        self.label_rsquared.setText(_translate("MainWindow", "R^2"))
        self.label_beta.setText(_translate("MainWindow", "beta"))
        self.label_alpha.setText(_translate("MainWindow", "alpha"))
        self.label_toffset.setText(_translate("MainWindow", "t0 (s)"))
        self.label_AUC.setText(_translate("MainWindow", "AUC"))
        self.label_peaktime.setText(_translate("MainWindow", "Time to Peak (s)"))
        self.label_timedensitycurve.setText(_translate("MainWindow", "Time Density Curve"))
        self.label_MTT.setText(_translate("MainWindow", "Mean Transit Time (s)"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.apply.setText(_translate("MainWindow", "Apply"))

from pyqtgraph import PlotWidget
