# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'COcalc1.ui'
#
# Created: Thu Jun 02 14:24:31 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CO_Calculator(object):
    def setupUi(self, CO_Calculator):
        CO_Calculator.setObjectName(_fromUtf8("CO_Calculator"))
        CO_Calculator.resize(800, 600)
        self.buttonBox = QtGui.QDialogButtonBox(CO_Calculator)
        self.buttonBox.setGeometry(QtCore.QRect(480, 560, 311, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.HUvalues = QtGui.QTableWidget(CO_Calculator)
        self.HUvalues.setGeometry(QtCore.QRect(40, 20, 141, 571))
        self.HUvalues.setRowCount(20)
        self.HUvalues.setColumnCount(1)
        self.HUvalues.setObjectName(_fromUtf8("HUvalues"))
        self.HUvalues.horizontalHeader().setVisible(False)
        self.HUvalues.horizontalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setVisible(True)
        self.HUvalues.verticalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setSortIndicatorShown(False)
        self.plotwidget = MatplotlibWidget(CO_Calculator)
        self.plotwidget.setGeometry(QtCore.QRect(190, 20, 601, 381))
        self.plotwidget.setObjectName(_fromUtf8("plotwidget"))
        self.label_bloodHU = QtGui.QLabel(CO_Calculator)
        self.label_bloodHU.setGeometry(QtCore.QRect(50, 0, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_bloodHU.setFont(font)
        self.label_bloodHU.setObjectName(_fromUtf8("label_bloodHU"))
        self.label_timedensitycurve = QtGui.QLabel(CO_Calculator)
        self.label_timedensitycurve.setGeometry(QtCore.QRect(370, 0, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timedensitycurve.setFont(font)
        self.label_timedensitycurve.setObjectName(_fromUtf8("label_timedensitycurve"))
        self.CurveFitResults = QtGui.QGroupBox(CO_Calculator)
        self.CurveFitResults.setGeometry(QtCore.QRect(200, 400, 271, 80))
        self.CurveFitResults.setObjectName(_fromUtf8("CurveFitResults"))
        self.label_rsquared = QtGui.QLabel(self.CurveFitResults)
        self.label_rsquared.setGeometry(QtCore.QRect(180, 20, 31, 16))
        self.label_rsquared.setObjectName(_fromUtf8("label_rsquared"))
        self.alpha = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.alpha.setGeometry(QtCore.QRect(20, 40, 40, 24))
        self.alpha.setMouseTracking(False)
        self.alpha.setObjectName(_fromUtf8("alpha"))
        self.rsquared = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.rsquared.setGeometry(QtCore.QRect(170, 40, 40, 24))
        self.rsquared.setMouseTracking(False)
        self.rsquared.setObjectName(_fromUtf8("rsquared"))
        self.beta = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.beta.setGeometry(QtCore.QRect(70, 40, 40, 24))
        self.beta.setMouseTracking(False)
        self.beta.setObjectName(_fromUtf8("beta"))
        self.AUC = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.AUC.setGeometry(QtCore.QRect(220, 40, 40, 24))
        self.AUC.setMouseTracking(False)
        self.AUC.setObjectName(_fromUtf8("AUC"))
        self.label_beta = QtGui.QLabel(self.CurveFitResults)
        self.label_beta.setGeometry(QtCore.QRect(80, 20, 31, 16))
        self.label_beta.setObjectName(_fromUtf8("label_beta"))
        self.label_alpha = QtGui.QLabel(self.CurveFitResults)
        self.label_alpha.setGeometry(QtCore.QRect(30, 20, 31, 16))
        self.label_alpha.setObjectName(_fromUtf8("label_alpha"))
        self.label_toffset = QtGui.QLabel(self.CurveFitResults)
        self.label_toffset.setGeometry(QtCore.QRect(130, 20, 31, 16))
        self.label_toffset.setObjectName(_fromUtf8("label_toffset"))
        self.t0 = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.t0.setGeometry(QtCore.QRect(120, 40, 40, 24))
        self.t0.setMouseTracking(False)
        self.t0.setObjectName(_fromUtf8("t0"))
        self.label_AUC = QtGui.QLabel(self.CurveFitResults)
        self.label_AUC.setGeometry(QtCore.QRect(230, 20, 31, 16))
        self.label_AUC.setObjectName(_fromUtf8("label_AUC"))
        self.inputDataGroup = QtGui.QGroupBox(CO_Calculator)
        self.inputDataGroup.setGeometry(QtCore.QRect(200, 500, 271, 91))
        self.inputDataGroup.setObjectName(_fromUtf8("inputDataGroup"))
        self.HUtoIodineConversion = QtGui.QPlainTextEdit(self.inputDataGroup)
        self.HUtoIodineConversion.setGeometry(QtCore.QRect(220, 60, 40, 24))
        self.HUtoIodineConversion.setMouseTracking(False)
        self.HUtoIodineConversion.setObjectName(_fromUtf8("HUtoIodineConversion"))
        self.timeInterval = QtGui.QPlainTextEdit(self.inputDataGroup)
        self.timeInterval.setGeometry(QtCore.QRect(90, 20, 40, 24))
        self.timeInterval.setMouseTracking(False)
        self.timeInterval.setObjectName(_fromUtf8("timeInterval"))
        self.baselineInput = QtGui.QPlainTextEdit(self.inputDataGroup)
        self.baselineInput.setGeometry(QtCore.QRect(220, 20, 40, 24))
        self.baselineInput.setMouseTracking(False)
        self.baselineInput.setObjectName(_fromUtf8("baselineInput"))
        self.label_baseline = QtGui.QLabel(self.inputDataGroup)
        self.label_baseline.setGeometry(QtCore.QRect(150, 20, 71, 20))
        self.label_baseline.setObjectName(_fromUtf8("label_baseline"))
        self.label_HUConversion = QtGui.QLabel(self.inputDataGroup)
        self.label_HUConversion.setGeometry(QtCore.QRect(100, 60, 121, 16))
        self.label_HUConversion.setObjectName(_fromUtf8("label_HUConversion"))
        self.label_tinterval = QtGui.QLabel(self.inputDataGroup)
        self.label_tinterval.setGeometry(QtCore.QRect(10, 20, 91, 20))
        self.label_tinterval.setObjectName(_fromUtf8("label_tinterval"))
        self.analysisResultsGroup = QtGui.QGroupBox(CO_Calculator)
        self.analysisResultsGroup.setGeometry(QtCore.QRect(490, 400, 291, 111))
        self.analysisResultsGroup.setObjectName(_fromUtf8("analysisResultsGroup"))
        self.label_MTT = QtGui.QLabel(self.analysisResultsGroup)
        self.label_MTT.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.label_MTT.setObjectName(_fromUtf8("label_MTT"))
        self.cardiacOutput = QtGui.QPlainTextEdit(self.analysisResultsGroup)
        self.cardiacOutput.setGeometry(QtCore.QRect(130, 20, 50, 24))
        self.cardiacOutput.setMouseTracking(False)
        self.cardiacOutput.setReadOnly(True)
        self.cardiacOutput.setObjectName(_fromUtf8("cardiacOutput"))
        self.MTT = QtGui.QPlainTextEdit(self.analysisResultsGroup)
        self.MTT.setGeometry(QtCore.QRect(130, 80, 50, 24))
        self.MTT.setMouseTracking(False)
        self.MTT.setObjectName(_fromUtf8("MTT"))
        self.standardError = QtGui.QPlainTextEdit(self.analysisResultsGroup)
        self.standardError.setGeometry(QtCore.QRect(240, 20, 40, 24))
        self.standardError.setMouseTracking(False)
        self.standardError.setObjectName(_fromUtf8("standardError"))
        self.label_CO = QtGui.QLabel(self.analysisResultsGroup)
        self.label_CO.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.label_CO.setObjectName(_fromUtf8("label_CO"))
        self.label_peaktime = QtGui.QLabel(self.analysisResultsGroup)
        self.label_peaktime.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_peaktime.setObjectName(_fromUtf8("label_peaktime"))
        self.label_sterror = QtGui.QLabel(self.analysisResultsGroup)
        self.label_sterror.setGeometry(QtCore.QRect(190, 20, 51, 20))
        self.label_sterror.setObjectName(_fromUtf8("label_sterror"))
        self.peakTime = QtGui.QPlainTextEdit(self.analysisResultsGroup)
        self.peakTime.setGeometry(QtCore.QRect(130, 50, 50, 24))
        self.peakTime.setMouseTracking(False)
        self.peakTime.setObjectName(_fromUtf8("peakTime"))

        self.retranslateUi(CO_Calculator)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CO_Calculator.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CO_Calculator.reject)
        QtCore.QMetaObject.connectSlotsByName(CO_Calculator)

    def retranslateUi(self, CO_Calculator):
        CO_Calculator.setWindowTitle(_translate("CO_Calculator", "Cardiac Output Calculator", None))
        self.label_bloodHU.setText(_translate("CO_Calculator", "Blood Hounsfield Units", None))
        self.label_timedensitycurve.setText(_translate("CO_Calculator", "Time Density Curve", None))
        self.CurveFitResults.setTitle(_translate("CO_Calculator", "Curve Fit Results", None))
        self.label_rsquared.setText(_translate("CO_Calculator", "R^2", None))
        self.label_beta.setText(_translate("CO_Calculator", "beta", None))
        self.label_alpha.setText(_translate("CO_Calculator", "alpha", None))
        self.label_toffset.setText(_translate("CO_Calculator", "t0 (s)", None))
        self.label_AUC.setText(_translate("CO_Calculator", "AUC", None))
        self.inputDataGroup.setTitle(_translate("CO_Calculator", "Input Data", None))
        self.label_baseline.setText(_translate("CO_Calculator", "Baseline (HU)", None))
        self.label_HUConversion.setText(_translate("CO_Calculator", "HU/Iodine (HU/(mg/mL)) ", None))
        self.label_tinterval.setText(_translate("CO_Calculator", "Time Interval (s)", None))
        self.analysisResultsGroup.setTitle(_translate("CO_Calculator", "Analysis Results", None))
        self.label_MTT.setText(_translate("CO_Calculator", "Mean Transit Time (s)", None))
        self.label_CO.setText(_translate("CO_Calculator", "Cardiac Output (L/min)", None))
        self.label_peaktime.setText(_translate("CO_Calculator", "Time to Peak (s)", None))
        self.label_sterror.setText(_translate("CO_Calculator", "st. error", None))

from matplotlibwidget import MatplotlibWidget
