# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'COcalc.ui'
#
# Created: Tue Dec 06 15:54:54 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CO_Calculator(object):
    def setupUi(self, CO_Calculator):
        CO_Calculator.setObjectName(_fromUtf8("CO_Calculator"))
        CO_Calculator.resize(803, 600)
        self.buttonBox = QtGui.QDialogButtonBox(CO_Calculator)
        self.buttonBox.setGeometry(QtCore.QRect(320, 570, 471, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.HUvalues = QtGui.QTableWidget(CO_Calculator)
        self.HUvalues.setGeometry(QtCore.QRect(40, 20, 141, 571))
        self.HUvalues.setMouseTracking(False)
        self.HUvalues.setRowCount(20)
        self.HUvalues.setColumnCount(1)
        self.HUvalues.setObjectName(_fromUtf8("HUvalues"))
        self.HUvalues.horizontalHeader().setVisible(False)
        self.HUvalues.horizontalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setVisible(True)
        self.HUvalues.verticalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setSortIndicatorShown(False)
        self.plotwidget = MatplotlibWidget(CO_Calculator)
        self.plotwidget.setGeometry(QtCore.QRect(190, 20, 601, 381))
        self.plotwidget.setObjectName(_fromUtf8("plotwidget"))
        self.baselineInput = QtGui.QPlainTextEdit(CO_Calculator)
        self.baselineInput.setGeometry(QtCore.QRect(380, 500, 40, 24))
        self.baselineInput.setMouseTracking(False)
        self.baselineInput.setObjectName(_fromUtf8("baselineInput"))
        self.label_baseline = QtGui.QLabel(CO_Calculator)
        self.label_baseline.setGeometry(QtCore.QRect(330, 500, 46, 20))
        self.label_baseline.setObjectName(_fromUtf8("label_baseline"))
        self.label_CO = QtGui.QLabel(CO_Calculator)
        self.label_CO.setGeometry(QtCore.QRect(500, 410, 111, 20))
        self.label_CO.setObjectName(_fromUtf8("label_CO"))
        self.cardiacOutput = QtGui.QPlainTextEdit(CO_Calculator)
        self.cardiacOutput.setGeometry(QtCore.QRect(610, 410, 61, 24))
        self.cardiacOutput.setMouseTracking(False)
        self.cardiacOutput.setReadOnly(True)
        self.cardiacOutput.setObjectName(_fromUtf8("cardiacOutput"))
        self.label_bloodHU = QtGui.QLabel(CO_Calculator)
        self.label_bloodHU.setGeometry(QtCore.QRect(50, 0, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_bloodHU.setFont(font)
        self.label_bloodHU.setObjectName(_fromUtf8("label_bloodHU"))
        self.label_tinterval = QtGui.QLabel(CO_Calculator)
        self.label_tinterval.setGeometry(QtCore.QRect(200, 500, 91, 20))
        self.label_tinterval.setObjectName(_fromUtf8("label_tinterval"))
        self.timeInterval = QtGui.QPlainTextEdit(CO_Calculator)
        self.timeInterval.setGeometry(QtCore.QRect(280, 500, 40, 24))
        self.timeInterval.setMouseTracking(False)
        self.timeInterval.setObjectName(_fromUtf8("timeInterval"))
        self.standardError = QtGui.QPlainTextEdit(CO_Calculator)
        self.standardError.setGeometry(QtCore.QRect(740, 410, 51, 24))
        self.standardError.setMouseTracking(False)
        self.standardError.setObjectName(_fromUtf8("standardError"))
        self.label_sterror = QtGui.QLabel(CO_Calculator)
        self.label_sterror.setGeometry(QtCore.QRect(690, 410, 51, 20))
        self.label_sterror.setObjectName(_fromUtf8("label_sterror"))
        self.peakTime = QtGui.QPlainTextEdit(CO_Calculator)
        self.peakTime.setGeometry(QtCore.QRect(610, 440, 61, 24))
        self.peakTime.setMouseTracking(False)
        self.peakTime.setObjectName(_fromUtf8("peakTime"))
        self.label_peaktime = QtGui.QLabel(CO_Calculator)
        self.label_peaktime.setGeometry(QtCore.QRect(500, 440, 81, 16))
        self.label_peaktime.setObjectName(_fromUtf8("label_peaktime"))
        self.MTT = QtGui.QPlainTextEdit(CO_Calculator)
        self.MTT.setGeometry(QtCore.QRect(610, 470, 61, 24))
        self.MTT.setMouseTracking(False)
        self.MTT.setObjectName(_fromUtf8("MTT"))
        self.label_MTT = QtGui.QLabel(CO_Calculator)
        self.label_MTT.setGeometry(QtCore.QRect(500, 470, 111, 16))
        self.label_MTT.setObjectName(_fromUtf8("label_MTT"))
        self.label_timedensitycurve = QtGui.QLabel(CO_Calculator)
        self.label_timedensitycurve.setGeometry(QtCore.QRect(370, 0, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timedensitycurve.setFont(font)
        self.label_timedensitycurve.setObjectName(_fromUtf8("label_timedensitycurve"))
        self.CurveFitResults = QtGui.QGroupBox(CO_Calculator)
        self.CurveFitResults.setGeometry(QtCore.QRect(190, 400, 301, 80))
        self.CurveFitResults.setObjectName(_fromUtf8("CurveFitResults"))
        self.label_rsquared = QtGui.QLabel(self.CurveFitResults)
        self.label_rsquared.setGeometry(QtCore.QRect(190, 20, 31, 16))
        self.label_rsquared.setObjectName(_fromUtf8("label_rsquared"))
        self.alpha = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.alpha.setGeometry(QtCore.QRect(0, 40, 51, 24))
        self.alpha.setMouseTracking(False)
        self.alpha.setObjectName(_fromUtf8("alpha"))
        self.rsquared = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.rsquared.setGeometry(QtCore.QRect(180, 40, 51, 24))
        self.rsquared.setMouseTracking(False)
        self.rsquared.setObjectName(_fromUtf8("rsquared"))
        self.beta = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.beta.setGeometry(QtCore.QRect(60, 40, 51, 24))
        self.beta.setMouseTracking(False)
        self.beta.setObjectName(_fromUtf8("beta"))
        self.AUC = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.AUC.setGeometry(QtCore.QRect(240, 40, 51, 24))
        self.AUC.setMouseTracking(False)
        self.AUC.setObjectName(_fromUtf8("AUC"))
        self.label_beta = QtGui.QLabel(self.CurveFitResults)
        self.label_beta.setGeometry(QtCore.QRect(70, 20, 31, 16))
        self.label_beta.setObjectName(_fromUtf8("label_beta"))
        self.label_alpha = QtGui.QLabel(self.CurveFitResults)
        self.label_alpha.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.label_alpha.setObjectName(_fromUtf8("label_alpha"))
        self.label_toffset = QtGui.QLabel(self.CurveFitResults)
        self.label_toffset.setGeometry(QtCore.QRect(130, 20, 31, 16))
        self.label_toffset.setObjectName(_fromUtf8("label_toffset"))
        self.t0 = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.t0.setGeometry(QtCore.QRect(120, 40, 51, 24))
        self.t0.setMouseTracking(False)
        self.t0.setObjectName(_fromUtf8("t0"))
        self.label_AUC = QtGui.QLabel(self.CurveFitResults)
        self.label_AUC.setGeometry(QtCore.QRect(250, 20, 31, 16))
        self.label_AUC.setObjectName(_fromUtf8("label_AUC"))
        self.label_HUConversion = QtGui.QLabel(CO_Calculator)
        self.label_HUConversion.setGeometry(QtCore.QRect(200, 540, 141, 16))
        self.label_HUConversion.setObjectName(_fromUtf8("label_HUConversion"))
        self.HUtoIodineConversion = QtGui.QPlainTextEdit(CO_Calculator)
        self.HUtoIodineConversion.setGeometry(QtCore.QRect(380, 540, 40, 24))
        self.HUtoIodineConversion.setMouseTracking(False)
        self.HUtoIodineConversion.setObjectName(_fromUtf8("HUtoIodineConversion"))

        self.retranslateUi(CO_Calculator)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CO_Calculator.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CO_Calculator.reject)
        QtCore.QMetaObject.connectSlotsByName(CO_Calculator)

    def retranslateUi(self, CO_Calculator):
        CO_Calculator.setWindowTitle(_translate("CO_Calculator", "Cardiac Output Calculator", None))
        self.label_baseline.setText(_translate("CO_Calculator", "Baseline", None))
        self.label_CO.setText(_translate("CO_Calculator", "Cardiac Output (L/min)", None))
        self.label_bloodHU.setText(_translate("CO_Calculator", "Blood Hounsfield Units", None))
        self.label_tinterval.setText(_translate("CO_Calculator", "Time Interval (s)", None))
        self.label_sterror.setText(_translate("CO_Calculator", "Std. Error", None))
        self.label_peaktime.setText(_translate("CO_Calculator", "Time to Peak (s)", None))
        self.label_MTT.setText(_translate("CO_Calculator", "Mean Transit Time (s)", None))
        self.label_timedensitycurve.setText(_translate("CO_Calculator", "Time Density Curve", None))
        self.CurveFitResults.setTitle(_translate("CO_Calculator", "Curve Fit Results", None))
        self.label_rsquared.setText(_translate("CO_Calculator", "R^2", None))
        self.label_beta.setText(_translate("CO_Calculator", "beta", None))
        self.label_alpha.setText(_translate("CO_Calculator", "alpha", None))
        self.label_toffset.setText(_translate("CO_Calculator", "t0 (s)", None))
        self.label_AUC.setText(_translate("CO_Calculator", "AUC", None))
        self.label_HUConversion.setText(_translate("CO_Calculator", "HU/Iodine (HU/(mg/mL)) ", None))

from matplotlibwidget import MatplotlibWidget
