# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cocalc_mainwindow.ui'
#
# Created: Thu Jun 08 15:39:55 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(799, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_CO = QtGui.QLabel(self.centralwidget)
        self.label_CO.setGeometry(QtCore.QRect(480, 500, 121, 20))
        self.label_CO.setObjectName(_fromUtf8("label_CO"))
        self.peakTime = QtGui.QPlainTextEdit(self.centralwidget)
        self.peakTime.setGeometry(QtCore.QRect(600, 530, 50, 24))
        self.peakTime.setMouseTracking(False)
        self.peakTime.setObjectName(_fromUtf8("peakTime"))
        self.label_tinterval = QtGui.QLabel(self.centralwidget)
        self.label_tinterval.setGeometry(QtCore.QRect(190, 410, 91, 20))
        self.label_tinterval.setObjectName(_fromUtf8("label_tinterval"))
        self.label_baseline = QtGui.QLabel(self.centralwidget)
        self.label_baseline.setGeometry(QtCore.QRect(320, 410, 46, 20))
        self.label_baseline.setObjectName(_fromUtf8("label_baseline"))
        self.label_sterror = QtGui.QLabel(self.centralwidget)
        self.label_sterror.setGeometry(QtCore.QRect(660, 500, 51, 20))
        self.label_sterror.setObjectName(_fromUtf8("label_sterror"))
        self.label_bloodHU = QtGui.QLabel(self.centralwidget)
        self.label_bloodHU.setGeometry(QtCore.QRect(30, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_bloodHU.setFont(font)
        self.label_bloodHU.setObjectName(_fromUtf8("label_bloodHU"))
        self.CurveFitResults = QtGui.QGroupBox(self.centralwidget)
        self.CurveFitResults.setGeometry(QtCore.QRect(470, 410, 281, 71))
        self.CurveFitResults.setObjectName(_fromUtf8("CurveFitResults"))
        self.label_rsquared = QtGui.QLabel(self.CurveFitResults)
        self.label_rsquared.setGeometry(QtCore.QRect(170, 20, 31, 16))
        self.label_rsquared.setObjectName(_fromUtf8("label_rsquared"))
        self.alpha = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.alpha.setGeometry(QtCore.QRect(10, 40, 40, 24))
        self.alpha.setMouseTracking(False)
        self.alpha.setObjectName(_fromUtf8("alpha"))
        self.rsquared = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.rsquared.setGeometry(QtCore.QRect(159, 40, 41, 24))
        self.rsquared.setMouseTracking(False)
        self.rsquared.setObjectName(_fromUtf8("rsquared"))
        self.beta = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.beta.setGeometry(QtCore.QRect(60, 40, 40, 24))
        self.beta.setMouseTracking(False)
        self.beta.setObjectName(_fromUtf8("beta"))
        self.AUC = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.AUC.setGeometry(QtCore.QRect(209, 40, 61, 24))
        self.AUC.setMouseTracking(False)
        self.AUC.setObjectName(_fromUtf8("AUC"))
        self.label_beta = QtGui.QLabel(self.CurveFitResults)
        self.label_beta.setGeometry(QtCore.QRect(70, 20, 31, 16))
        self.label_beta.setObjectName(_fromUtf8("label_beta"))
        self.label_alpha = QtGui.QLabel(self.CurveFitResults)
        self.label_alpha.setGeometry(QtCore.QRect(20, 20, 31, 16))
        self.label_alpha.setObjectName(_fromUtf8("label_alpha"))
        self.label_toffset = QtGui.QLabel(self.CurveFitResults)
        self.label_toffset.setGeometry(QtCore.QRect(120, 20, 31, 16))
        self.label_toffset.setObjectName(_fromUtf8("label_toffset"))
        self.t0 = QtGui.QPlainTextEdit(self.CurveFitResults)
        self.t0.setGeometry(QtCore.QRect(110, 40, 40, 24))
        self.t0.setMouseTracking(False)
        self.t0.setObjectName(_fromUtf8("t0"))
        self.label_AUC = QtGui.QLabel(self.CurveFitResults)
        self.label_AUC.setGeometry(QtCore.QRect(230, 20, 31, 16))
        self.label_AUC.setObjectName(_fromUtf8("label_AUC"))
        self.MTT = QtGui.QPlainTextEdit(self.centralwidget)
        self.MTT.setGeometry(QtCore.QRect(600, 560, 50, 24))
        self.MTT.setMouseTracking(False)
        self.MTT.setObjectName(_fromUtf8("MTT"))
        self.standardError = QtGui.QPlainTextEdit(self.centralwidget)
        self.standardError.setGeometry(QtCore.QRect(710, 500, 40, 24))
        self.standardError.setMouseTracking(False)
        self.standardError.setObjectName(_fromUtf8("standardError"))
        self.baselineInput = QtGui.QPlainTextEdit(self.centralwidget)
        self.baselineInput.setGeometry(QtCore.QRect(370, 410, 40, 24))
        self.baselineInput.setMouseTracking(False)
        self.baselineInput.setObjectName(_fromUtf8("baselineInput"))
        self.HUvalues = QtGui.QTableWidget(self.centralwidget)
        self.HUvalues.setGeometry(QtCore.QRect(20, 40, 141, 571))
        self.HUvalues.setMouseTracking(True)
        self.HUvalues.setRowCount(20)
        self.HUvalues.setColumnCount(1)
        self.HUvalues.setObjectName(_fromUtf8("HUvalues"))
        self.HUvalues.horizontalHeader().setVisible(False)
        self.HUvalues.horizontalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setVisible(True)
        self.HUvalues.verticalHeader().setCascadingSectionResizes(False)
        self.HUvalues.verticalHeader().setSortIndicatorShown(False)
        self.label_peaktime = QtGui.QLabel(self.centralwidget)
        self.label_peaktime.setGeometry(QtCore.QRect(510, 530, 81, 16))
        self.label_peaktime.setObjectName(_fromUtf8("label_peaktime"))
        self.label_timedensitycurve = QtGui.QLabel(self.centralwidget)
        self.label_timedensitycurve.setGeometry(QtCore.QRect(350, 0, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timedensitycurve.setFont(font)
        self.label_timedensitycurve.setObjectName(_fromUtf8("label_timedensitycurve"))
        self.cardiacOutput = QtGui.QPlainTextEdit(self.centralwidget)
        self.cardiacOutput.setGeometry(QtCore.QRect(600, 500, 50, 24))
        self.cardiacOutput.setMouseTracking(False)
        self.cardiacOutput.setReadOnly(True)
        self.cardiacOutput.setObjectName(_fromUtf8("cardiacOutput"))
        self.label_MTT = QtGui.QLabel(self.centralwidget)
        self.label_MTT.setGeometry(QtCore.QRect(490, 560, 111, 16))
        self.label_MTT.setObjectName(_fromUtf8("label_MTT"))
        self.timeInterval = QtGui.QPlainTextEdit(self.centralwidget)
        self.timeInterval.setGeometry(QtCore.QRect(270, 410, 40, 24))
        self.timeInterval.setMouseTracking(False)
        self.timeInterval.setObjectName(_fromUtf8("timeInterval"))
        self.reset = QtGui.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(540, 680, 75, 23))
        self.reset.setObjectName(_fromUtf8("reset"))
        self.apply = QtGui.QPushButton(self.centralwidget)
        self.apply.setGeometry(QtCore.QRect(670, 680, 75, 23))
        self.apply.setObjectName(_fromUtf8("apply"))
        self.PyQtGraph1 = PlotWidget(self.centralwidget)
        self.PyQtGraph1.setGeometry(QtCore.QRect(190, 30, 551, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.PyQtGraph1.setPalette(palette)
        self.PyQtGraph1.setAutoFillBackground(True)
        self.PyQtGraph1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);"))
        self.PyQtGraph1.setFrameShadow(QtGui.QFrame.Sunken)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.PyQtGraph1.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.PyQtGraph1.setForegroundBrush(brush)
        self.PyQtGraph1.setObjectName(_fromUtf8("PyQtGraph1"))
        self.IodinetoHUconversion = QtGui.QGroupBox(self.centralwidget)
        self.IodinetoHUconversion.setGeometry(QtCore.QRect(180, 450, 281, 51))
        self.IodinetoHUconversion.setObjectName(_fromUtf8("IodinetoHUconversion"))
        self.c = QtGui.QPlainTextEdit(self.IodinetoHUconversion)
        self.c.setGeometry(QtCore.QRect(200, 20, 41, 24))
        self.c.setMouseTracking(False)
        self.c.setObjectName(_fromUtf8("c"))
        self.a = QtGui.QPlainTextEdit(self.IodinetoHUconversion)
        self.a.setGeometry(QtCore.QRect(40, 20, 41, 24))
        self.a.setMouseTracking(False)
        self.a.setObjectName(_fromUtf8("a"))
        self.label_HU = QtGui.QLabel(self.IodinetoHUconversion)
        self.label_HU.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label_HU.setObjectName(_fromUtf8("label_HU"))
        self.label_I2plus = QtGui.QLabel(self.IodinetoHUconversion)
        self.label_I2plus.setGeometry(QtCore.QRect(90, 30, 41, 16))
        self.label_I2plus.setObjectName(_fromUtf8("label_I2plus"))
        self.b = QtGui.QPlainTextEdit(self.IodinetoHUconversion)
        self.b.setGeometry(QtCore.QRect(130, 20, 41, 24))
        self.b.setMouseTracking(False)
        self.b.setObjectName(_fromUtf8("b"))
        self.label_I = QtGui.QLabel(self.IodinetoHUconversion)
        self.label_I.setGeometry(QtCore.QRect(180, 30, 31, 16))
        self.label_I.setObjectName(_fromUtf8("label_I"))
        self.InjectionParameters = QtGui.QGroupBox(self.centralwidget)
        self.InjectionParameters.setGeometry(QtCore.QRect(180, 510, 281, 111))
        self.InjectionParameters.setObjectName(_fromUtf8("InjectionParameters"))
        self.volume = QtGui.QPlainTextEdit(self.InjectionParameters)
        self.volume.setGeometry(QtCore.QRect(150, 80, 41, 24))
        self.volume.setMouseTracking(False)
        self.volume.setObjectName(_fromUtf8("volume"))
        self.dilution = QtGui.QPlainTextEdit(self.InjectionParameters)
        self.dilution.setGeometry(QtCore.QRect(150, 20, 41, 24))
        self.dilution.setMouseTracking(False)
        self.dilution.setObjectName(_fromUtf8("dilution"))
        self.label_dilution = QtGui.QLabel(self.InjectionParameters)
        self.label_dilution.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_dilution.setObjectName(_fromUtf8("label_dilution"))
        self.label_concentration = QtGui.QLabel(self.InjectionParameters)
        self.label_concentration.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label_concentration.setObjectName(_fromUtf8("label_concentration"))
        self.concentration = QtGui.QPlainTextEdit(self.InjectionParameters)
        self.concentration.setGeometry(QtCore.QRect(150, 50, 41, 24))
        self.concentration.setMouseTracking(False)
        self.concentration.setObjectName(_fromUtf8("concentration"))
        self.label_volume = QtGui.QLabel(self.InjectionParameters)
        self.label_volume.setGeometry(QtCore.QRect(80, 80, 61, 16))
        self.label_volume.setObjectName(_fromUtf8("label_volume"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(180, 630, 141, 22))
        self.comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboBox.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.comboBox.setAcceptDrops(False)
        self.comboBox.setEditable(False)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_CO.setText(_translate("MainWindow", "Cardiac Output (L/min)", None))
        self.label_tinterval.setText(_translate("MainWindow", "Time Interval (s)", None))
        self.label_baseline.setText(_translate("MainWindow", "Baseline", None))
        self.label_sterror.setText(_translate("MainWindow", "st. error", None))
        self.label_bloodHU.setText(_translate("MainWindow", "Blood Hounsfield Units", None))
        self.CurveFitResults.setTitle(_translate("MainWindow", "Curve Fit Results", None))
        self.label_rsquared.setText(_translate("MainWindow", "R^2", None))
        self.label_beta.setText(_translate("MainWindow", "beta", None))
        self.label_alpha.setText(_translate("MainWindow", "alpha", None))
        self.label_toffset.setText(_translate("MainWindow", "t0 (s)", None))
        self.label_AUC.setText(_translate("MainWindow", "AUC", None))
        self.label_peaktime.setText(_translate("MainWindow", "Time to Peak (s)", None))
        self.label_timedensitycurve.setText(_translate("MainWindow", "Time Density Curve", None))
        self.label_MTT.setText(_translate("MainWindow", "Mean Transit Time (s)", None))
        self.reset.setText(_translate("MainWindow", "Reset", None))
        self.apply.setText(_translate("MainWindow", "Apply", None))
        self.IodinetoHUconversion.setTitle(_translate("MainWindow", "Iodine (mg/mL) to HU conversion", None))
        self.label_HU.setText(_translate("MainWindow", "HU = ", None))
        self.label_I2plus.setText(_translate("MainWindow", "I^2 +", None))
        self.label_I.setText(_translate("MainWindow", "I +", None))
        self.InjectionParameters.setTitle(_translate("MainWindow", "Injection Parameters", None))
        self.label_dilution.setText(_translate("MainWindow", "Dilution (Omnipque fraction)", None))
        self.label_concentration.setText(_translate("MainWindow", "Concentration (mg/mL)", None))
        self.label_volume.setText(_translate("MainWindow", "Volume (cc)", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select Scanner...", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Toshiba @ 100 keV", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Toshiba @ 120 keV", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "GE VCT @ 120 keV", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "GE VCT @ 100 keV", None))

from pyqtgraph import PlotWidget
